// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      // throw UnsupportedError(
      //   'DefaultFirebaseOptions have not been configured for windows - '
      //   'you can reconfigure this by running the FlutterFire CLI again.',
      // );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN5o4paKdoDPGHxEk2bKEdLlN9fvCAQdg',
    appId: '1:168151078817:web:7db15805f4f27d7d771de0',
    messagingSenderId: '168151078817',
    projectId: 'smart-gpt-ai-7f206',
    authDomain: 'smart-gpt-ai-7f206.firebaseapp.com',
    storageBucket: 'smart-gpt-ai-7f206.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN5o4paKdoDPGHxEk2bKEdLlN9fvCAQdg',
    appId: '1:168151078817:web:7db15805f4f27d7d771de0',
    messagingSenderId: '168151078817',
    projectId: 'smart-gpt-ai-7f206',
    authDomain: 'smart-gpt-ai-7f206.firebaseapp.com',
    storageBucket: 'smart-gpt-ai-7f206.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOqu0H-63-UILrJXZmtk7u-ehr12KsszI',
    appId: '1:168151078817:android:ee25483b2f9ae322771de0',
    messagingSenderId: '168151078817',
    projectId: 'smart-gpt-ai-7f206',
    storageBucket: 'smart-gpt-ai-7f206.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSkgtjzWGApw8xlQ9_xzEIqhconNaLJw0',
    appId: '1:168151078817:ios:b4376533d3c2b78d771de0',
    messagingSenderId: '168151078817',
    projectId: 'smart-gpt-ai-7f206',
    storageBucket: 'smart-gpt-ai-7f206.appspot.com',
    androidClientId:
        '168151078817-c9hnflafglm0gcbt7644dln4gs72cb7k.apps.googleusercontent.com',
    iosClientId:
        '168151078817-5ia1sg2ojsau8okcloe81femv7q3mr53.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartGptAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSkgtjzWGApw8xlQ9_xzEIqhconNaLJw0',
    appId: '1:168151078817:ios:2b0dce813212e465771de0',
    messagingSenderId: '168151078817',
    projectId: 'smart-gpt-ai-7f206',
    storageBucket: 'smart-gpt-ai-7f206.appspot.com',
    androidClientId:
        '168151078817-c9hnflafglm0gcbt7644dln4gs72cb7k.apps.googleusercontent.com',
    iosClientId:
        '168151078817-4mo3vn0213tv5nll6kq1s00p96n7k8d3.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartGptAi.RunnerTests',
  );
}
